### PR TITLE
Famous computer scientist website 

### PR DESCRIPTION
**Pull request by Ellsmore**
Disregard the commit about array work, I just wasn't sure on how to remove it.

I need to fix up a few things in regards to position, particularly in my header section. If I could get some tips on the following I would be happier than a fat kid eating cake.

1. How can I get my nav bar in my header section to stretch to the same width as my header background image.
2. What CSS can I use to make sure there is no gap between my header background image and the top of the browser.

Thanks mate!

### CODE REVIEW

**Comment by Ellsmore** [comment]
Difficulty: 4/10
How long: 3 hours
Struggled with: header (see previous comment)
More info on: ^

**Comment by cjbarnaby** [comment]
Hey Chris - I'm going to merge this in so I can download your code and test it to give you proper feedback. Will get back to you this morning!

**Comment by Ellsmore** [comment]
Too easy mate.

On Tue, Jun 21, 2016 at 8:35 AM, Chris Barnaby <notifications@github.com>
wrote:

> Hey Chris - I'm going to merge this in so I can download your code and
> test it to give you proper feedback. Will get back to you this morning!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cjbarnaby/WDI15_Homework/pull/9#issuecomment-227290802>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASeSCbU1JcfRpGr4DYghhHYBKCYm3FWKks5qNxXNgaJpZM4I28Ss>
> .
>



-- 
Regards,
Chris Ellsmore

**Comment by cjbarnaby** [comment]
Hey Chris, 

Good work so far, dude! You're definitely getting it. Just a few comments on the homework you've submitted to date - you didn't mention some of the homework specifically in your Pull Request, so you might not've been ready to actually submit them, but I'll just assume you were - the feedback should hopefully be useful in any case.

## Arrays

- **Chaining logical operators**: In your `maxOfThree` function, you have an expression `(num1 > (num2 && num3)`, which looks nice and tidy, but it doesn't work how you would expect it to - `(num2 && num3)` evaluates to `num3` - so `(2 && 5)` evaluates to `5` - it just evaluates to whatever the second 'operand' is. So `(num1 > (num2 && num3))` actually just says `num1 > num3`. So if you were to pass in `num1 = 5; num2 = 10000; num3 = 1)`, the expression will evaluate `5 > 1` (`true`), ignoring the 10000 altogether. 
- **Using loops to save time and make your code more dynamic** - Your solutions to `sumArray` and `multiplyArray` are perfectly fine - no problems there. Just something to keep in mind is that, when we're dealing with arrays, we can use loops to make your code more dynamic - ie, so we don't have to change any code if we add/remove elements from the array. 

```
var sumArray = function(arr)
  var sum = 0;
  for (var i = 0; i < arr.length; i++) {
    sum += arr[i];
} 
return sum;

sumArray(numbers);
```

It's more lines of code, it's a little harder to read, but it's more dynamic and that makes me happy.

- **Using temporary variables** - Again, your `findLongestWord` function is perfect, but I just wanted to show a different way of approaching the problem - we could have declared a variable called, say, `longestWord` and given it an initial, nominal value of an empty string `""`. Then we could loop through each word in our array, compare its `.length` to that of the `longestWord variable and, if it is longer, change the value of `longestWord` to be that word.

- **`.filter` ** - Saw you had a crack at using `.filter` - that's a tough concept to get your head around 2 days into JS (it confuses the crap out of me). To be honest, I can't even figure out how to use `.filter` with an anonymous function _inside a named function_ like you've tried to. The only way I can think of doing it (where you have two arguments being passed to the function) is to have the callback to a named function, not an anonymous function. So...

```
var findLongWords = function(array, min) {
 return function(word) {
  return (word.length > 5);
 }
}

words.filter(longWords(5));
```

God, that's a nightmare. 

##Famous Computer Scientists

Great job with this! Okay, firstly, your specific questions:

-_"How can I get my nav bar in my header section to stretch to the same width as my header background image."_

If you open your browser's dev tools, right click on the nav bar and click 'inspect', this will open your browser's developer tools to the 'elements' tab with the element (a `<ul>` tag) selected - you'll see that the element has an orange box around it, indicating that it has a margin - if you look in the 'styles' box, you'll see it has a margin of `5px` on each side (`margin: 5px`). You can either change the margin of all `<ul>` tags in your CSS, or - probably a better idea - give that element a class, and set the margin of _that_ in your CSS:

HTML:
```
<ul class="nav-links> ... </ul>
```
CSS
```
.nav-links {
 margin: 5px 0px; 
}
```
(Setting two values for the margin property sets the top and bottom margins to the first value and the left and right margins to the second value);
 
-_"What CSS can I use to make sure there is no gap between my header background image and the top of the browser."_

Ugh. I hate this shit. Browsers have something called a 'user agent stylesheet', which are styles that the browser adds to an HTML document by default in some misguided attempt to be helpful. Fortunately, your own styles can override anything in the user agent stylesheet; unfortunately, what styles you need to change to get that white space to fuck off may depend on the contents of your html. In a lot of cases, since it's often just the user agent styling of the `body` element that's the problem, you can fix the 'white space at the top of the browser window' issue by putting this at the start of your CSS:

```
body {
  margin: 0;
}
```

Another thing you can do (which isn't a bad idea generally) is to include **normalize.css** above the reference to your own css in the HTML - this is pretty great for 'normalizing' the different styles different browsers add - check it out [normalize.css](https://necolas.github.io/normalize.css/).

In your case, though, neither of those things will fix it entirely, since the problem is that your first element is an h1 tag, and _that_ bastard has a default (user agent stylesheet) style of `-webkit-margin-before: 0.67em;`, which is adding most of that white space at the top. If you open your browser's developer tools, click on the element tab, expand the element tree and start scrolling over the elements from top to bottom, you'll quickly hit the one/s that have the additional margin. Then just make the margin-top of those elements `0` in your css:

```
h1:first-of-type {
  margin-top: 0;
}
body {
  margin-top: 0;
}
```

-**Assets paths** - avoid using (ie, don't use) absolute paths in the references to your own assets (images, css files, etc) and links. Just use relative paths - the browser will sort out the root path. When I pulled your code down, all your links and all your images were broken. Examples:

**Instead of this**: 
```
<img src="/Users/pellsmore/projects/02-html+css/homework/famous_computer_scientist_website/Images/ClaudeShannon.jpg" />
<a href="/Users/pellsmore/projects/02-html+css/homework/famous_computer_scientist_website/index.html">Biographies</a>
```

**Do this**:

```
<img src="Images/ClaudeShannon.jpg" />
<a href="index.html">Biographies</a>
```

Nice work with the site! Good inclusion of the maps and video embeds! And plus 10000 points for that picture of Richard Stallman (and finding that video of him eating his toe jam). 

Your CSS is also really solid - I really like how you've split the doc up into different sections like that. Also, it might seem like a minor thing, but your code is also really, really nicely formatted. Consistent formatting (spacing, indenting, etc) throughout, perfect indentation, etc. This is a great habit to have picked up so early.

Totally doesn't matter, but convention for HTML classes is to use dash-case rather than camelCase. A lot of people prefer camelCase, but yeah, most people tend to use dash-case. 

## Cat Walk

Looks like you had some big things planned for this guy 😸 ! Let me know if you ended up doing more on it and didn't push it up. But you got it walking across the screen, which - to be honest - is all I managed when I did the course :smile: . If you got stuck with this and are curious to know how to get it to work, come have a chat.

Good work so far, Chris. I know you haven't managed to get all your homework submitted, but don't sweat it - just let me know if there's anything you want a hand with (oftentimes during the course that'll be "yeah, everything", and that's fine - the course is brutal, and I'm happy to do whatever I can to help you guys feel more comfortable about what you're learning. 

Badger.

**Pull request merged**
