### PR TITLE
Homework for Wednesday, June 16 - Fansite

### PR DESCRIPTION
**Pull request by katmlee**
Hi Badger,

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
6- wasn't particularly difficult by took a lot of time

Was there anything that you struggled with?
I had issues with integrating the font-awesome folder, aligning sections within the div and implementing changes to flex.  

Is there anything that you'd like some further information on?
I'm looking forward to doing more in responsive. 

Roughly how long did it take?
~5 hours

### CODE REVIEW

**Comment by katmlee** [comment]
Hi Badger, 

This comment is for Thursday's HW, Cat Walk. 

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible?
7- it wasn't terribly hard but ran into some issues.

Was there anything that you struggled with?
 Issues with going backwards and also stopping in the middle of the page after walking back and forth multiple times. 

Is there anything that you'd like some further information on?
Above question. 

Roughly how long did it take?
~2 hours

**Comment by katmlee** [comment]
Hi Badger,

This comment is for Friday's HW, ATM.

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible?
6- I was able to work through it myself to just get it done but I'm sure there are DRYer ways to execute. 

Was there anything that you struggled with?
Nothing too crazy.

Is there anything that you'd like some further information on?
Making it less duplicative. 

Roughly how long did it take?
~2 hours

Thanks! The tryjquery took me forever though. I wasn't really getting it at first.

**Comment by cjbarnaby** [comment]
Hey Katrina - I'm going to merge this into my repo then review (just letting you know so you don't think I'm just merging it in and ignoring all your comments and questions!).

**Comment by cjbarnaby** [comment]
Hey Katrina, 

Here's some feedback on your last few bits and pieces of homework.

## Fan Site

Awesome job on this! Really nice visual design, too (esp those `heroImage` divs). 

- Let me know if you want any help with aligning content next time round - it can be a pain. Not sure if I've sent you these before, but here are a few things worth reading - [this](https://www.w3.org/Style/Examples/007/center.en.html), [this](https://css-tricks.com/centering-css-complete-guide/) and [this](http://learnlayout.com/). The first one, in particular, is great - it looks like garbage, and it talks about 'centering' specifically, but getting your head around how to position elements using the visual formatting model is essential. 

- Your `<footer>` tags should really be inside your `<body>` tags. 

- Ideally, try to keep your scripts out of your HTML using `<script src="myscript.js"></script>` rather than having inline JS. 

- Same for CSS - while you have a div with a number of styles specified inline with the HTML`<div display=inline-block; style='overflow:hidden;height:400px;width:100%;'>`, you could give that sucker a class or id and set those styles in your CSS. 

Excellent job!

## ATM

Great job with this too. It is really difficult refactor your code to remove repetition, especially in the little amount of time you were given to complete this. Having said that, the approach you've taken is a good one - get it working with a shit tonne of code before trying to make it DRY. Break it down into smaller chunks, get them all working, then refactor. 

A few things before moving on to tips for refactoring:

- You should have only one `$(document).ready(function() { });` per JS file. 
- Good use of global variables!
- A very minor point that does not impact the validity of your code, but I'd consider including more spaces in your code - everyone does this a little differently, JT includes a lot more spaces than I do, for example, but this is a pretty good guide that no one will bitch about you following [https://github.com/rwaldron/idiomatic.js#whitespace](Idiomatic JS - White Space). 

Example - This:
```javascript
 if(savingsBalance===0){
```
...is harder to read than this:

```javascript 
 if ( savingsBalance === 0 ) {
```

As for refactoring to remove duplication - this is something that comes with practice, and I'm sure you're already better at refactoring than you were when you submitted this homework, but my starting point would be to:

1. Look for repeated assignments for the one variable within a function or control structure (loops, conditionals, etc) - can you assign values to those variables earlier on to save you from having to assign them twice? Example: `checkingAcct = $('#checking-amount').val();` is assigned twice in a conditional (once in the `if`, once in the `else`), and the value assigned is the same in both cases, so lets move that up before the conditional starts.
2. Look at functions that appear to perform a _similar_ action, the specifics of which differ depending upon a particular condition;
3. Compare those two functions, and see what the differences are - these differences are likely to be the arguments for your function, or variables that you will set within your function. In this case, it's probably more likely to be the latter. Instead of `$("#checking-balance").text("$"+checkingBalance)`, how can you make it `$balance.text(balance)`? You would need to set the variables `$balance` and `balance` depending on how the function was called. So how do you determine, from within the function, what values should be assigned?
4. Often it would be by passing arguments into the function (like `accountType` and `transactionType`), but in this case, where you're using jQuery's `.on()` method, it's probably easier to:
 i. Have a single listener for different elements using the [multiple selector syntax](https://api.jquery.com/multiple-selector/) (eg `$('#savings-deposit, #checking-deposit').on("click", function() {});` and then using `$(this)` within your function to work out what triggered the event `($(this).attr("id"))` would return "#savings-deposit", for example). Then have a conditional at the very start of your function in which you assign all the values for balance, amount, etc, depending on what `$(this)` was. 

## Cat Walk

Wow. That is... that is something. Haha. 

Great work. Re: your question on getting the cat to stop in the middle on its way back, I would have put thrown something like this in your catWalk function: 
```
    if ((parseInt(img.style.left) <= (window.innerWidth / 2)) && (walkingRight === false)) {
        dancingCat();
    }
```
And then your dancingCat() function would clear the setInterval timer (`window.clearInterval(id);`), hide the first cat (img.style.opacity = "1"), show a second cat for a period of time (using a setTimeout) and call the walk function again (or, most likely, a slightly different one so that it walks from the middle of the page through to the end before calling the walk function again and generating a new timer).

I think you could've made life a bit easier for yourself by storing more values in variables (for example - you use this multiple times, might be worth storing it in a variable before you enter that bunch of conditionals: `(parseInt(img.style.left))`

You're doing a bang-up job, K-Money. Keep it up!

Badger.

**Comment by katmlee** [comment]
Hey Badger,

Thanks for the feedback, I'll take a look at the resources over the
weekend. Also, shoot! i forgot to write comments on mta.rb  :( should i add
them and repush?

Thanks,

Katrina

On 29 June 2016 at 08:10, Chris Barnaby <notifications@github.com> wrote:

> Hey Katrina,
>
> Here's some feedback on your last few bits and pieces of homework.
> Fan Site
>
> Awesome job on this! Really nice visual design, too (esp those heroImage
> divs).
>
>    -
>
>    Let me know if you want any help with aligning content next time round
>    - it can be a pain. Not sure if I've sent you these before, but here are a
>    few things worth reading - this
>    <https://www.w3.org/Style/Examples/007/center.en.html>, this
>    <https://css-tricks.com/centering-css-complete-guide/> and this
>    <http://learnlayout.com/>. The first one, in particular, is great - it
>    looks like garbage, and it talks about 'centering' specifically, but
>    getting your head around how to position elements using the visual
>    formatting model is essential.
>    -
>
>    Your <footer> tags should really be inside your <body> tags.
>    -
>
>    Ideally, try to keep your scripts out of your HTML using <script
>    src="myscript.js"></script> rather than having inline JS.
>    -
>
>    Same for CSS - while you have a div with a number of styles specified
>    inline with the HTML<div display=inline-block;
>    style='overflow:hidden;height:400px;width:100%;'>, you could give that
>    sucker a class or id and set those styles in your CSS.
>
> Excellent job!
> ATM
>
> Great job with this too. It is really difficult refactor your code to
> remove repetition, especially in the little amount of time you were given
> to complete this. Having said that, the approach you've taken is a good one
> - get it working with a shit tonne of code before trying to make it DRY.
> Break it down into smaller chunks, get them all working, then refactor.
>
> A few things before moving on to tips for refactoring:
>
>    - You should have only one $(document).ready(function() { }); per JS
>    file.
>    - Good use of global variables!
>    - A very minor point that does not impact the validity of your code,
>    but I'd consider including more spaces in your code - everyone does this a
>    little differently, JT includes a lot more spaces than I do, for example,
>    but this is a pretty good guide that no one will bitch about you following
>    https://github.com/rwaldron/idiomatic.js#whitespace
>    <http://Idiomatic%20JS%20-%20White%20Space>.
>
> Example - This:
>
>  if(savingsBalance===0){
>
> ...is harder to read than this:
>
>  if ( savingsBalance === 0 ) {
>
> As for refactoring to remove duplication - this is something that comes
> with practice, and I'm sure you're already better at refactoring than you
> were when you submitted this homework, but my starting point would be to:
>
>    1. Look for repeated assignments for the one variable within a
>    function or control structure (loops, conditionals, etc) - can you assign
>    values to those variables earlier on to save you from having to assign them
>    twice? Example: checkingAcct = $('#checking-amount').val(); is
>    assigned twice in a conditional (once in the if, once in the else),
>    and the value assigned is the same in both cases, so lets move that up
>    before the conditional starts.
>    2. Look at functions that appear to perform a *similar* action, the
>    specifics of which differ depending upon a particular condition;
>    3. Compare those two functions, and see what the differences are -
>    these differences are likely to be the arguments for your function, or
>    variables that you will set within your function. In this case, it's
>    probably more likely to be the latter. Instead of
>    $("#checking-balance").text("$"+checkingBalance), how can you make it
>    $balance.text(balance)? You would need to set the variables $balance
>    and balance depending on how the function was called. So how do you
>    determine, from within the function, what values should be assigned?
>    4. Often it would be by passing arguments into the function (like
>    accountType and transactionType), but in this case, where you're using
>    jQuery's .on() method, it's probably easier to: i. Have a single
>    listener for different elements using the multiple selector syntax
>    <https://api.jquery.com/multiple-selector/> (eg $('#savings-deposit,
>    #checking-deposit').on("click", function() {}); and then using $(this)
>    within your function to work out what triggered the event
>    ($(this).attr("id")) would return "#savings-deposit", for example).
>    Then have a conditional at the very start of your function in which you
>    assign all the values for balance, amount, etc, depending on what
>    $(this) was.
>
> Cat Walk
>
> Wow. That is... that is something. Haha.
>
> Great work. Re: your question on getting the cat to stop in the middle on
> its way back, I would have put thrown something like this in your catWalk
> function:
>
>     if ((parseInt(img.style.left) <= (window.innerWidth / 2)) && (walkingRight === false)) {
>         dancingCat();
>     }
>
> And then your dancingCat() function would clear the setInterval timer (
> window.clearInterval(id);), hide the first cat (img.style.opacity = "1"),
> show a second cat for a period of time (using a setTimeout) and call the
> walk function again (or, most likely, a slightly different one so that it
> walks from the middle of the page through to the end before calling the
> walk function again and generating a new timer).
>
> I think you could've made life a bit easier for yourself by storing more
> values in variables (for example - you use this multiple times, might be
> worth storing it in a variable before you enter that bunch of conditionals:
> (parseInt(img.style.left))
>
> You're doing a bang-up job, K-Money. Keep it up!
>
> Badger.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cjbarnaby/WDI15_Homework/pull/10#issuecomment-229199895>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANM6j8uDe789Qd49fWGBdAqn2aML0tFGks5qQZvegaJpZM4I28Tv>
> .
>



-- 
Cornell University | School of Hotel Administration, '11
Cell: 609.216.5174 | E-Mail: kml66@cornell.edu

**Pull request merged**
