### PR TITLE
Homework day 4

### PR DESCRIPTION
**Pull request by armandoltx**
Hi Chris,
Finished homework day 4. Objects in JS.
Homework: Rectangle, Triangle, Bank.

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible:
I'd say it was a 8 in difficulty, I need to improve the way I approach the exercises.

Was there anything that you struggled with?
I struggled with return, I do not really know when to use it or not. Also the last part of the bonus, transferring money from accounts... No idea.

Is there anything that you'd like some further information on? 
I need more practice, and learn how to use return...

Roughly how long did it take? 3.5 hours

Thanks! Armando.

### CODE REVIEW

**Comment by armandoltx** [comment]
Hi Chris,
Finished homework day 4. Objects in JS.
Homework: Rectangle, Triangle, Bank.

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible:
I'd say it was a 8 in difficulty, I need to improve the way I approach the exercises.

Was there anything that you struggled with?
I struggled with return, I do not really know when to use it or not. Also the last part of the bonus, transferring money from accounts... No idea.

Is there anything that you'd like some further information on? 
I need more practice, and learn how to use return...

Roughly how long did it take? 3.5 hours

Thanks! Armando.

**Comment by cjbarnaby** [comment]
Hey Armando, 

Would you mind moving all non-homework documents out of your homework directory? So, all the code-alongs you do during class, your non-homework afternoon labs, your warmup exercises. The homework repo should just be for homework, if that's okay - makes it a lot easier for me to see what I need to review. If you want to leave this til Monday we can do it together. Basically, just put all that stuff anywhere outside of the WDI15_Homework folder on your computer.

**Comment by armandoltx** [comment]
Hello,
I think I already removed all the non-homework out of the pull request. Also I added the MTA lab

**Comment by cjbarnaby** [comment]
### Verbing

Good choice using the `.endsWith()` method. This definitely satisfies the problem (which specifies the lowercase 'ing'), but - for future reference - if you _wanted_ catch matches of upper case OR lowercase words ending with 'ing', you could use `.match(), along with the `$` symbol (end of string) and `i` flag (checks any case):

```javascript
if (str.match(/ing$/i)) {
 //  code here 
}

### Word Guesser

All looks good - one suggestion is to store the results to be console logged in a variable called `result`, or similar, then simply `return result` at the end of the function. 

#### Return

Re: your question about how `return` works - there is a pretty decent explanation in [Week 1 Day 5](https://cjbarnaby.gitbooks.io/wdi-15/content/week_01/wk01_day05.html) of the GitBook. This may make more sense when we get to Ruby, but there is no 'implicit return' in Javascript functions. When we're learning JS in the console, we use `console.log()` a lot to get functions to output something we can see, but really, unless there is a `return` statement in a function, it doesn't actually output anything that we can use. For example, if I had a function called `fullName` which takes two arguments (a first name and a surname) and returns a concatenation of the two names, here is the difference between using and not using a return statement:

```javascript
var firstName = "Armando";
var secondName = "Ruiz";

// with no return statement:
var fullName = function(first, second) {
  (first + " " + second);
}

fullName(firstName, secondName);
// => undefined

// with a return statement:
var fullName = function(first, second) {
  return (first + " " + second);
}

fullName(firstName, secondName) {
// => "Armondo Ruiz" 
```

Without the return statement, a function won't return anything (or, rather, it will return `undefined`).

#### Transfer function

I'm sure you've gotten into this over the weekend with MTA, but you could have saved yourself a fair bit of effort and time by calling the deposit and withdraw functions from within your transfer function. 

Great job so far, Armando!!

**Comment by cjbarnaby** [comment]
Hey Armando, 

### MTA 
Great job on MTA! 

This might sound like a very basic point, but your variable names were great - it was obvious what each function and each variable represented without having to wade through the code itself to try and figure it out. 

Generally, your syntax and formatting is great - just keep an eye on your indenting. While your indenting was good within each loop or conditional, it was inconsistent between functions, or between loops/conditionals in the one function. A minor point that doesn't impact the validity of your code, but it makes it easier for anyone else reading your code.

There are only two other things I would really comment on for you to consider in future:

1. **DRY - 'Don't Repeat Yourself'** - your `singleLineTrip` and the first half of your `multiLineTrip` functions are almost identical. You could re-write your `singleLineTrip` function so that your `multiLineTrip` function simply called the `singleLineTrip` function and returned the result for your `multiLineTrip` function to use.
2. **Error Handling** - what if a user enters in a station that doesn't exist? Or enters a station that doesn't exist for a particular line? They get a weird error in the console. This wasn't explicitly stated in the problem, but it's something to think about - handling 'edge cases'. 

Nice work, Armando!!

**Comment by armandoltx** [comment]
Thanks, I will have a look later tonight ( if I have time and create functions to clean up my code).

**Pull request merged**
