### PR TITLE
Submitting homework for week02

### PR DESCRIPTION
**Pull request by TriptiWani**
Fansite:
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
6 - 

Was there anything that you struggled with?;
Figuring out which element to be used for displays was difficult for me. like p or div or header or h1. Implementing css was also difficult

Is there anything that you'd like some further information on?;
yea.. would like to know mor about useful css tricks. I wasnt able to put nice looking quotation marks for quotes, how to do that. how to include font-awesome.

Roughly how long did it take?
2 - 2.5 hours

Cat:
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
5
Was there anything that you struggled with?;
my cat wasnt walking in backwards direction. Then moon walking, then finally it did walk

Is there anything that you'd like some further information on?;
Please let me know how to incorporate the degree stuff, like transformation of cat in degrees.

Roughly how long did it take?
1.5 hrs

ATM:
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
5, it involved many things to be taken care of. I kinda liked the problem/

Was there anything that you struggled with?;
implementing the logic to take only 2 digits after decimal, then i cud do it after sometime.

Is there anything that you'd like some further information on?;
yea.. if I dnt restrict the number of digits in input, how many digits wud be considered. Like when I entered a big number, the balance went exponential, and then the code wasnt working correctly.

Roughly how long did it take?
around 3.5 -4 hrs

### CODE REVIEW

**Comment by TriptiWani** [comment]
Hey badger,

I have submitted the Ruby homework for Monday and tuesday - calculator and mta.

Also, below are the queries from the last homework -  ATM -
'Keypress event issue' and the 'toggleClass issue'

Calculator:
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
2
Was there anything that you struggled with?;
initially with paranthesis stuff, but was good later
Is there anything that you'd like some further information on?;
not at the moment

Roughly how long did it take?
approx 1 hour

MTA:
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
2
Was there anything that you struggled with?;
yes, with variable scope
Is there anything that you'd like some further information on?;
I think need to dive more into the scope thing
Roughly how long did it take?
45 mins

**Comment by TriptiWani** [comment]
Hello Badger,

Submitting the homework for the Movie Database using Sinatra

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
5

Was there anything that you struggled with?;
yes, caught myself into loops inside loops, which was later on factored. Then calling two erbs inside one get block was a little tricky thing

Is there anything that you'd like some further information on?;
There is much more to learn about sinatra. Few queries on my mind currently:
- where do I define if I am not using layout.erb, using some other erb in place of this
- if my public folder is named something else, where to specify that

Roughly how long did it take?
2-2.5 hrs

**Comment by cjbarnaby** [comment]
Hey Tripti, 

I'm going to merge this into my repo so I can pull it down and test things more easily, I'll add my feedback here this afternoon.

Badge

**Comment by TriptiWani** [comment]
Sure Badger :)

**Comment by cjbarnaby** [comment]
Hey Tripti, 

Great work - some feedback below.

## Fansite

First, the specific queries you had:

- **Figuring out which element to be used** - I'd suggest having a read of the [GitBook Notes for Week 2 Day 2](https://cjbarnaby.gitbooks.io/wdi-15/content/week_02/wk02_day02.html) and then the [MDN HTML Element Reference](https://developer.mozilla.org/en/docs/Web/HTML/Element). The generic content sectioning element is the `<div>` - it's just a block-level container element that has no special meaning. That's the most commonly used element for grouping content together for positioning, styling, etc. Any group of elements can be wrapped in a `<div>`. Many other sectioning elements are just `<div>`s with some semantic meaning - for example `<header>` and `<article>` and `<section>`, etc. Have a read of those two references and let me know if you have any questions. 

- **Implementing CSS was difficult** - This comes with practice, but if you want a reference work, Duckett's HTML & CSS is great. Otherwise, for looking stuff up as you go, MDN, as always, is great. While I wouldn't ordinarily point people towards www.w3schools.com, that is handy for a succinct (if not always 100% accurate) starting point for css properties and values. Having said all that, your CSS looks good - a few little things:

 - There were a few duplicated rules in there - you have, for example, specified rules for `<h2>` twice. The browser will, in this case, just take the last rule (though the rules of specificity may change that - there's a bit on specificity in the GitBook notes for Week 2 Day 2 and a link to another resource on this). 
- There were a few duplicated declarations in there as well - again, the browser will just take the second declaration and ignore the first.
- Redundant styles - there were a few spots where you had declared values for properties multiple times unnecessarily. For example:

```
img{
  align:middle;
  background-color:#c1c1c5;
  border-radius: 1em;
  margin-top: 1em;
}
.otherPageImg{
  align:middle;
  background-color:#c1c1c5;
  border-radius: 1em;
  margin-top: 1em;
  width: 195px;
  height:285px;

``
- since everything with a class of .otherPageImg is also an `<img>` element, you don't need to declare those first five property/values in .otherPageImg. 

- **Including Font Awesome** - If you download Font Awesome from the fontawesome.io homepage, you can put all those folders in your project's directory then just add this link in your HTML's head tag (before your own CSS):

```
<link rel="stylesheet" href="css/font-awesome.min.css">
```

You don't need those `less` and `scss` directories for a site like this one, since you aren't using less or sass.

Hope that helps! Let me know if you have any questions. 

Will send feedback on the rest of your stuff this arvo.

**Comment by TriptiWani** [comment]
Thanks Badger. Will first check the 'GitBook Notes for Week 2 Day 2' and then MDN documentation. Will update my css as well as per your comments :)

**Comment by cjbarnaby** [comment]
## Catwalk

Hi Tripti, 

Some feedback on your Catwalk:

- First, your specific question: "Please let me know how to incorporate the degree stuff, like transformation of cat in degrees." Are you asking how to animate that property? If so, there are a few ways to do it - some in CSS (using animations) and some using JS (including vanilla JS or jQuery's .animate() method). In keeping with how you've handled the movement of the cat (using img.style.left), I'll show you the vanilla JS way. First, we'd need to declare the following at the start of your JS:

```
var deg = 0;
img.style.transform = 'rotate(' + deg + 'deg)'; 
```

Then, just inside your `catwalkRight()` function:

```
  deg += 5;
  img.style.transform = 'rotate(' + deg + 'deg)';
```

Unfortunately, you still need to vendor prefix `transform` CSS properties, your references to `transform` would need to be:

```
   img.style.WebkitTransform = 'rotate(' + deg + 'deg)'; 
   img.style.MsTransform = 'rotate(' + deg + 'deg)'; 
   img.style.transform = 'rotate(' + deg + 'deg)'; 
```

If you don't _need_ to animate this using Javascript and can use CSS instead, using the CSS animation property along with keyframes is the most straightforward way:

```
.rotate {
    -webkit-animation:spin 4s linear infinite;
    -moz-animation:spin 4s linear infinite;
    animation:spin 4s linear infinite;
}
@-moz-keyframes spin { 100% { -moz-transform: rotate(360deg); } }
@-webkit-keyframes spin { 100% { -webkit-transform: rotate(360deg); } }
@keyframes spin { 100% { -webkit-transform: rotate(360deg); transform:rotate(360deg); } }
```

A few other little things:

1. Try to keep styles out of your HTML wherever possible (eg ``).
2. In your `catWalkLeft` function, your cat isn't turning around because the test `  if (newLeft === 160 )` is never being satisfied (due to the fact that, as your reducing the value  of `img.style.left`, it's never exactly 160px). A safer test would be `  if (newLeft < 160 )`.

Good job on the CatWalk!

**Pull request merged**
